=== ebullient/ttrpg-convert-cli/examples/config/config.schema.json
{
  "$schema" : "https://json-schema.org/draft/2020-12/schema",
  "$defs" : {
    "Map(String,String)" : {
      "type" : "object"
    }
  },
  "type" : "object",
  "properties" : {
    "exclude" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "excludePattern" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "from" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "images" : {
      "type" : "object",
      "properties" : {
        "copyExternal" : {
          "type" : "boolean"
        },
        "copyInternal" : {
          "type" : "boolean"
        },
        "fallbackPaths" : {
          "$ref" : "#/$defs/Map(String,String)"
        },
        "internalRoot" : {
          "type" : "string"
        }
      }
    },
    "include" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "includeGroup" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "includePattern" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "onlyReferencedTables" : {
      "type" : "boolean"
    },
    "paths" : {
      "type" : "object",
      "properties" : {
        "compendium" : {
          "type" : "string"
        },
        "rules" : {
          "type" : "string"
        }
      }
    },
    "racesAsSpecies" : {
      "type" : "boolean"
    },
    "reprintBehavior" : {
      "type" : "string",
      "enum" : [ "newest", "edition", "all" ]
    },
    "sources" : {
      "type" : "object",
      "properties" : {
        "adventure" : {
          "type" : "array",
          "items" : {
            "type" : "string"
          }
        },
        "book" : {
          "type" : "array",
          "items" : {
            "type" : "string"
          }
        },
        "defaultSource" : {
          "$ref" : "#/$defs/Map(String,String)"
        },
        "homebrew" : {
          "type" : "array",
          "items" : {
            "type" : "string"
          }
        },
        "reference" : {
          "type" : "array",
          "items" : {
            "type" : "string"
          }
        },
        "toolsRoot" : {
          "type" : "string"
        }
      }
    },
    "splitRules" : {
      "type" : "boolean"
    },
    "tagPrefix" : {
      "type" : "string"
    },
    "template" : {
      "$ref" : "#/$defs/Map(String,String)"
    },
    "useDiceRoller" : {
      "type" : "boolean"
    },
    "yamlStatblocks" : {
      "type" : "boolean"
    }
  }
}

=== ebullient/ttrpg-convert-cli/examples/config/config.pf2e.json
{
  "sources" : {
    "reference" : [
      "CRB",
      "GMG"
    ],
    "book" : [
      "crb",
      "gmg"
    ]
  },
  "paths" : {
    "compendium" : "compendium/",
    "rules" : "compendium/rules/"
  },
  "include" : [
    "ability|buck|b1"
  ],
  "exclude" : [
    "background|insurgent|apg"
  ],
  "excludePattern" : [
    "background|.*|lowg"
  ],
  "reprintBehavior" : "newest",
  "template" : {
    "ability" : "../path/to/ability2md.txt"
  },
  "useDiceRoller" : true,
  "tagPrefix" : "ttrpg-cli",
  "images" : { }
}

=== ebullient/ttrpg-convert-cli/src/test/resources/sources-homebrew.json
{
  "from": [
    "Ar3",
    "B:P",
    "BH2022",
    "BookofLairs",
    "DM14",
    "DM:BFS",
    "DMG", 
    "ExploringEberron",
    "ermis-bg",
    "FleeMortals",
    "GH",
    "GHMG",
    "MM",
    "NerzugalsExtendedBestiary",
    "PHB", 
    "Psion",
    "SC",
    "SCoC",
    "TalentPsionicsOpenPlaytestRound2",
    "TBHA",
    "TDCSR",
    "ToB3",
    "TheLostLands",
    "arkadia",
    "dndwiki_bestbackgrounds"
  ],
  "include": [
    "race|changeling|mpmm"
  ],
  "exclude": [
    "monster|expert|dc",
    "monster|expert|sdw",
    "monster|expert|slw"
  ],
  "excludePattern": [
    "race|.*|dmg"
  ],
  "template": {
    "monster": "src/test/resources/other/monster-all.txt"
  }
}

=== ebullient/ttrpg-convert-cli/src/test/resources/5e/sources.json
{
  "sources": {
    "book": [
      "PHB",
      "DMG",
      "XGE",
      "TCE"
    ],
    "adventure": [
      "WbtW"
    ]
  },
  "include": [
    "race|changeling|mpmm"
  ],
  "exclude": [
    "monster|expert|dc",
    "monster|expert|sdw",
    "monster|expert|slw"
  ],
  "excludePattern": [
    "race\\|.*\\|dmg"
  ]
}

=== ebullient/ttrpg-convert-cli/src/test/resources/5e/sources-homebrew.json
{
  "sources": {
    "adventure": [
      "LMOP"
    ],
    "book": [
      "PSA"
    ],
    "homebrew": [
      "src/test/resources/5e/psion.json",
      "src/test/resources/5e/ermis-bg.json",
      "sources/5e-homebrew/adventure/Anthony Joyce; The Blood Hunter Adventure.json",
      "sources/5e-homebrew/adventure/Arcanum Worlds; Odyssey of the Dragonlords.json",
      "sources/5e-homebrew/adventure/JVC Parry; Call from the Deep.json",
      "sources/5e-homebrew/adventure/Kobold Press; Book of Lairs.json",
      "sources/5e-homebrew/background/D&D Wiki; Featured Quality Backgrounds.json",
      "sources/5e-homebrew/book/Ghostfire Gaming; Stibbles Codex of Companions.json",
      "sources/5e-homebrew/book/MCDM Productions; Arcadia Issue 3.json",
      "sources/5e-homebrew/class/D&D Wiki; Swashbuckler.json",
      "sources/5e-homebrew/class/Foxfire94; Vampire.json",
      "sources/5e-homebrew/class/KibblesTasty; Inventor.json",
      "sources/5e-homebrew/class/Matthew Mercer; Blood Hunter (2022).json",
      "sources/5e-homebrew/class/badooga; Badooga's Psion.json",
      "sources/5e-homebrew/collection/Arcana Games; Arkadia.json",
      "sources/5e-homebrew/collection/Darrington Press; Tal’Dorei Campaign Setting Reborn.json",
      "sources/5e-homebrew/collection/Ghostfire Gaming; Grim Hollow - Campaign Guide - 2014.json",
      "sources/5e-homebrew/collection/Ghostfire Gaming; Grim Hollow - Campaign Guide - 2024.json",
      "sources/5e-homebrew/collection/Ghostfire Gaming; Grim Hollow - The Monster Grimoire.json",
      "sources/5e-homebrew/collection/Jasmine Yang; Hamund's Herbalism Handbook.json",
      "sources/5e-homebrew/collection/Keith Baker; Exploring Eberron.json",
      "sources/5e-homebrew/collection/Kobold Press; Deep Magic 14 Elemental Magic.json",
      "sources/5e-homebrew/collection/Kobold Press; Deep Magic.json",
      "sources/5e-homebrew/collection/Loot Tavern; Heliana's Guide To Monster Hunting.json",
      "sources/5e-homebrew/collection/MCDM Productions; The Talent and Psionics Open Playtest Round 2.json",
      "sources/5e-homebrew/creature/Dragonix; Monster Manual Expanded III.json",
      "sources/5e-homebrew/creature/Kobold Press; Creature Codex.json",
      "sources/5e-homebrew/creature/Kobold Press; Tome of Beasts 2.json",
      "sources/5e-homebrew/creature/Kobold Press; Tome of Beasts.json",
      "sources/5e-homebrew/creature/MCDM Productions; Flee, Mortals! preview.json",
      "sources/5e-homebrew/creature/MCDM Productions; Flee, Mortals!.json",
      "sources/5e-homebrew/creature/Nerzugal Role-Playing; Nerzugal's Extended Bestiary.json",
      "sources/5e-homebrew/deity/Frog God Games; The Lost Lands.json",
      "sources/5e-homebrew/race/Middle Finger of Vecna; Archon.json",
      "sources/5e-homebrew/spell/LaserLlama; LaserLlama's Compendium of Spells.json",
      "sources/5e-homebrew/subclass/LaserLlama; Druid Circles.json"
    ],
    "reference": [
      "DMG",
      "MM",
      "EGW",
      "FTD",
      "PHB",
      "XPHB"
    ]
  },
  "include": [
    "race|changeling|mpmm"
  ],
  "exclude": [
    "monster|expert|dc",
    "monster|expert|sdw",
    "monster|expert|slw"
  ],
  "excludePattern": [
    "race\\|.*\\|dmg"
  ],
  "template": {
    "background": "examples/templates/tools5e/images-background2md.txt",
    "item": "examples/templates/tools5e/images-item2md.txt",
    "monster": "src/test/resources/other/monster-all.txt",
    "object": "examples/templates/tools5e/images-object2md.txt",
    "race": "examples/templates/tools5e/images-race2md.txt",
    "spell": "examples/templates/tools5e/images-spell2md.txt",
    "vehicle": "examples/templates/tools5e/images-vehicle2md.txt"
  },
  "useDiceRoller": true,
  "yamlStatblocks": true
}

=== ebullient/ttrpg-convert-cli/examples/config/config.5e.json
{
  "sources" : {
    "toolsRoot" : "local/5etools/data",
    "reference" : [
      "DMG"
    ],
    "adventure" : [
      "LMoP"
    ],
    "book" : [
      "PHB"
    ],
    "homebrew" : [
      "homebrew/collection/Kobold Press; Deep Magic 14 Elemental Magic.json"
    ]
  },
  "paths" : {
    "compendium" : "/compendium/",
    "rules" : "/compendium/rules/"
  },
  "include" : [
    "race|changeling|mpmm"
  ],
  "includeGroup" : [
    "familiars"
  ],
  "exclude" : [
    "monster|expert|dc",
    "monster|expert|sdw",
    "monster|expert|slw"
  ],
  "excludePattern" : [
    "race|.*|dmg"
  ],
  "reprintBehavior" : "newest",
  "template" : {
    "background" : "examples/templates/tools5e/images-background2md.txt"
  },
  "useDiceRoller" : true,
  "yamlStatblocks" : true,
  "tagPrefix" : "ttrpg-cli",
  "images" : {
    "internalRoot" : "local/path/for/remote/images",
    "copyInternal" : true,
    "copyExternal" : true
  }
}

=== ebullient/ttrpg-convert-cli/src/test/resources/5e/sources-2014-book-adventure.json
{
  "paths": {
    "rules": "/ru les/",
    "compendium": "/compend ium/"
  },
  "sources": {
    "adventure": [
      "WBtW",
      "MOT-NSS",
      "DIP",
      ""
    ],
    "book": [
      "PHB",
      "MOT",
      ""
    ],
    "reference": [
      "DMG",
      "XGE",
      "TCE",
      ""
    ],
    "homebrew": [
      ""
    ]
  },
  "include": [
    "race|changeling|mpmm"
  ],
  "exclude": [
    "monster|expert|dc",
    "monster|expert|sdw",
    "monster|expert|slw"
  ],
  "excludePattern": [
    "race\\|.*\\|dmg"
  ]
}
